services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    networks:
      - app-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: calorie-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://root:rootpassword@mongodb:27017/calorie-count?authSource=admin
      - JWT_SECRET=secret123456789
      - USDA_API_KEY=qIZTwHYXHsiOqJINtfwqSJu9wWb4b6uuFEGhXCke
      - NODE_ENV=development
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: calorie-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
      - build_cache:/app/.next
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:5000
      - WATCHPACK_POLLING=true
    networks:
      - app-network

volumes:
  mongodb_data:
  node_modules:
  build_cache:

networks:
  app-network:
    driver: bridge
